inputs:
  name: xxx # 云函数名称，默认为 ${name}-${stage}-${app}
  src: ./ # 项目代码路径，默认写法，新建特定命名的 COS Bucket 并上传
  handler: index.main_handler #入口
  runtime: Nodejs10.15 # 运行环境 默认 Nodejs10.15
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  environment: #  环境变量
    variables: #  环境变量对象
      TEST: value
  layers: #layer配置
    - name: scfLayer #  layer名称
      version: 1 #  版本
  events: # 触发器配置
    - timer: # 定时触发器
        parameters:
          cronExpression: '*/5 * * * * * *' # 每5秒触发一次
          enable: true
